version: "3"

services:
  server:
    build: server/
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    #persistent storage, check that directory is good ++
    volumes:
      - ../data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
