FROM node:14

WORKDIR /manywords/

# install git to be able to watch from the container
RUN apt-get update -qq
RUN apt-get install -y build-essential
RUN apt-get install -y git

COPY server ./server
COPY jest.config.js ./
COPY .git ./

COPY package*.json ./
RUN npm install

CMD ./node_modules/.bin/jest --watch --coverage