version: "3"

services:
  web-app:
    build:
      context: ./web-app/
      dockerfile: dev.Dockerfile
    container_name: manywords-web-app
    environment:
      EXTEND_ESLINT: "true"
      REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    volumes:
      # to allow hot reloading
      - ./web-app:/web-app
    ports:
      - 3000:3000
    stdin_open: true

  server:
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    container_name: manywords-server
    environment:
      NODE_ENV: "development"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      SERVER_PORT: ${SERVER_PORT}
    # to allow hot reloading
    volumes:
      - ./server:/server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    depends_on:
      - mongo

  database-seeder:
    build:
      context: ./tools
    container_name: manywords-database-seeder
    environment:
      NODE_ENV: "development"
    volumes:
      - ./exercises:/exercises
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: manywords-mongo
    volumes:
      - /mongo/data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: manywords-mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

