version: "3"

services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    container_name: manywords-test-server
    env_file:
      - /.env.test
    environment:
      NODE_ENV: "test"
      JWT_SIGNATURE: ${JWT_SIGNATURE}
      SERVER_PORT: ${SERVER_PORT}
    # to allow hot reloading
    volumes:
      - ./server:/server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mongo

  database-seeder:
    build:
      context: ./tools
    container_name: manywords-test-database-seeder
    environment:
      NODE_ENV: "test"
    volumes:
      - ./exercises:/exercises
    depends_on:
      - mongo

  mongo:
    env_file:
      - .env.test
    image: mongo
    restart: always
    container_name: manywords-test-mongo
    volumes:
      - /mongo/testData:/data/db
    ports:
      - 27018:27017

  mongo-express:
    image: mongo-express
    container_name: manywords-test-mongo-express
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - mongo
