version: "3"

services:
  client:
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    container_name: many_words-client
    environment:
      BROWSER: "none"
      REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    # to allow hot reloading
    volumes:
      - ./client:/client
    ports:
      - 3000:3000

  server:
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    container_name: many_words-server
    environment:
      NODE_ENV: "development"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
    # to allow hot reloading
    volumes:
      - ./server:/server
    ports:
      - 3001:3001
      - 9229:9229
    depends_on:
      - mongo

  database-seeder:
    build:
      context: ./tools
    container_name: many_words-database-seeder
    volumes:
      - ./exercises:/exercises
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: many_words-mongo
    volumes:
      - /mongo/data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: many_words-mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

