version: "3"

services:
  client:
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/client
    ports:
      - 3000:3000

  server:
    build:
      context: ./server/
      dockerfile: prod.Dockerfile
    environment:
      NODE_ENV: "production"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./server:/server
    ports:
      - 3001:3001
      - 9229:9229
    depends_on:
      - mongo

  exercises:
    build: 
      context: ./exercises
      dockerfile: Dockerfile
    volumes:
      - exercises:/exercises

  database-seeder:
    build:
      context: ./tools
      dockerfile: dev.Dockerfile
    restart: on-failure
    volumes:
      - exercises:/exercises
    environment:
      NODE_ENV: "production"
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    depends_on:
      - mongo
      - exercises

  mongo:
    image: mongo
    restart: always
    volumes:
      - /mongo/data:/data/db
      - ../mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

volumes: 
  dbdata:
  exercises:
