import React from "react";

// TODO: use camelCase for lessons and topics
export const languages = {
  english: {
    language: "english",
    navbar: {
      home: "Home",
      login: "Log in",
    },
    navigation: {
      loginWith: "Log in with",
      logout: "Log out",
      weakWords: "Weak words",
      tryAgain: "Try again",
      toContinue: "Continue",
      quit: "Menu",
    },
    about: {
      title: "About Many Words",
      description: `  As you may have noticed, Many Words is in the early stages of its development.
      This WebApp is not for profit : you will see no ads and your privacy will be respected (no tracker or third-party cookies).
      If you have questions, suggestions, or have noticed a bug or a mistake, please contact me via Twitter or Github.
      The codebase is open-source under the MIT license, any help is welcome!`,
      roadmap: "Roadmap",
      roadmapShortTerm: "Short term",
      roadmapLongTerm: "Long term",
      shortTerm1: "More content: from 2000 to 3000 words",
      shortTerm2:
        "Weak words: focus on the hardest words for you, globally or by theme",
      shortTerm3: "Lesson levels: 3 different levels of difficulty",
      shortTerm4: "Progressive learning: unlock lessons progressively",
      shortTerm5:
        "Continuous learning: learn without leaving the exercise screen, the app selects your weak words and next lesson.",
      shortTerm6: "We're out of beta!",
      longTerm1: "Add a third language: Spanish most probably",
      longTerm2: "Learn the vocabulary of 2 or 3 languages at the same time",
      longTerm3: "Publish a smartphone app",
      longTerm4: "Climb to 5 languages",
    },
    home: {
      about: "About",
      back: "Cancel",
      confirm: "Confirm",
      confirmDeletion:
        "All your data will be permanently deleted. Are you sure?",
      deleteAccount: "Delete my account",
      deleteSuccess: "You account has been permanently deleted",
      deleteWaiting: "Deletion in progress",
      discover: "Or start learning without registering",
      discoverButton: "Let's go !",
      featuresFree: "100% Free",
      featuresProgress: "Earn stars",
      featuresWords: "750+ Words",
      frenchEnglishVocabulary: "French vocabulary basics",
      lessons: "Lessons",
      login: "Log in",
      logoutProgress: "Logging out",
      logoutSuccess: "You were successfully disconnected",
      mainTitle: "Improve your French vocabulary",
      noStats: "It's time to start learning !",
      progressTitle: "Global completion",
      register: "",
      resumeLearning: "Resume learning",
      words: "Words",
    },
    topics: {
      animals: "Animals",
      clothes: "Clothes",
      colors: "Colors",
      food: "Food",
      habitation: "Habitation",
      humanBody: "Human body",
      nature: "Nature",
      numbers: "Numbers",
      socialLife: "Social life",
      society: "Society",
      time: "Time",
      vegetal: "Vegetal",
    },
    lessons: {
      accessories: "Accessories",
      agriculture: "Agriculture",
      animalsBasics: "Animals",
      birds: "Birds",
      buildings: "Buildings",
      closeFamily: "Close family",
      clothesBasics: "Clothes 1",
      constructionMaterials: "Materials",
      constructionTools: "Tools",
      days: "Days",
      drinks: "Drinks",
      earth: "Earth",
      farmAnimals: "Farm animals",
      firstNumbers: "First numbers",
      foodBasics: "Food 1",
      foods: "Foods",
      fruits: "Fruits",
      furniture: "Furniture",
      head: "Head",
      house: "House",
      housing: "Housing",
      humanBodyBasics: "Human body",
      humanBeings: "Human beings",
      identity: "Identity",
      insects: "Insects",
      introduction: "Introduction",
      largeNumbers: "Large numbers",
      limbs: "Limbs",
      mainColors: "Main colors",
      mammals1: "Mammals",
      months: "Months",
      moreClothes: "Clothes 2",
      moreFruitsAndVegetables: "Fruits and Vegetables 2",
      moreNumbers: "More numbers",
      natureBasics: "Nature",
      organs: "Organs",
      plants: "Plants",
      rooms: "Rooms",
      sea: "Sea",
      seaAnimals: "Sea animals",
      senses: "Senses",
      timeBasics: "Time 1",
      timeDescription1: "Time 2",
      timeDescription2: "Time 3",
      timeDivisions: "Time divisions",
      town: "Town",
      transports: "Transports",
      trees: "Trees",
      universe: "Universe",
      vegetables: "Vegetables",
      vegetalBasics: "Vegetal",
      weather1: "Weather 1",
      weather2: "Weather 2",
    },
    translateIn: "Translate in",
    french: "French",
    english: "English",
    correct: [
      "Excellent",
      "You're right",
      "Perfect",
      "Nothing to say",
      "Impressive",
      "Target hit",
      "Great",
      "Good",
      "Indeed",
      "Easy",
      "Well done",
      "Nice",
      "Way to go",
      "Wonderful",
      "Incredible",
      "Bravo",
      "Et voilà",
    ],
    correctAnswer: "Right answer",
    noMistake: "Congratulations, you've made no mistake !",
    oneMistake: "Great, it is almost perfect !",
    oneMistakeInstruction: "Mind this word :",
    moreMistakes: "Take a moment to memorize the words you missed :",
    masculine: "masculine",
    feminine: "feminine",
    singular: "singular",
    plural: "plural",
    definite: "definite",
    indefinite: "indefinite",
    revision: "Revision",
  },

  /* --------------------        FRENCH     ------------------- */

  french: {
    language: "french",
    navbar: {
      home: "Accueil",
      login: "Connexion",
    },
    navigation: {
      loginWith: "Connexion avec",
      logout: "Déconnexion",
      weakWords: "Mots faibles",
      toContinue: "Continuer",
      tryAgain: "Réessayer",
      quit: "Menu",
    },
    about: {
      title: "À propos de Many Words",
      description: `Comme tu as pu le remarquer, Many Words est 
      encore à la phase précoce de son développement. Cette application 
      n'est pas à but lucratif : tu ne trouveras aucune publicité et 
      ta vie privée sera respectée (pas de traqueurs ni de cookies tiers). Si tu as des questions, remarques,
       ou si tu souhaites signaler des bugs, contacte-moi via Twitter ou Github. 
       Le code est open-source sous licence MIT, toute aide est la bienvenue!`,
      roadmap: "Fonctionnalités futures",
      roadmapShortTerm: "Court terme",
      roadmapLongTerm: "Long terme",
      shortTerm1: "Plus de contenu: entre 2000 et 3000 mots",
      shortTerm2:
        "Mots faibles: concentre-toi sur tes points faibles, globalement ou par thème",
      shortTerm3: "Niveaux de leçons: 3 niveaux de difficulté",
      shortTerm4:
        "Apprentissage progressif: débloque les leçons au fur et à mesure",
      shortTerm5:
        "Apprentissage continu: apprends sans revenir au menu, l'application sélectionne tes points faibles et les prochaines leçons",
      shortTerm6: "Fin de la beta!",
      longTerm1: "Ajout d'une troisième langue: l'Espagnol très probablement",
      longTerm2: "Apprends le vocabulaire de 2 ou 3 langues simultanément",
      longTerm3: "Publication d'une application pour smartphone",
      longTerm4: "Ajouter jusqu'à 5 languages",
    },
    home: {
      about: "À propos",
      back: "Annuler",
      confirm: "Confirmer",
      confirmDeletion:
        "Toutes tes données seront supprimées définitivement. Es-tu sûr?",
      deleteAccount: "Supprimer mon compte",
      deleteSuccess: "Ton compte a été définitivement supprimé",
      deleteWaiting: "Suppression en cours",
      discover: "Pas besoin de se connecter pour commencer",
      discoverButton: "C'est parti !",
      featuresFree: "100% Gratuit",
      featuresProgress: "Parcours personnalisé",
      featuresWords: "5000+ Mots",
      frenchEnglishVocabulary: "Vocabulaire anglais basique",
      lessons: "Leçons",
      login: "Se connecter",
      logoutProgress: "Déconnexion en cours",
      logoutSuccess: "Tu es maintenant déconnecté",
      mainTitle: "Enrichis ton vocabulaire anglais",
      noStats: "C'est l'heure d'apprendre !",
      progressTitle: "Avancement global",
      register: "",
      resumeLearning: "Continuer l'apprentissage",
      words: "Mots",
    },
    topics: {
      animals: "Animaux",
      clothes: "Vêtements",
      colors: "Couleurs",
      food: "Nourriture",
      habitation: "Habitation",
      humanBody: "Corps humain",
      nature: "Nature",
      numbers: "Nombres",
      socialLife: "Vie sociale",
      society: "Société",
      time: "Temps",
      vegetal: "Végétaux",
    },
    lessons: {
      accessories: "Accessoires",
      agriculture: "Agriculture",
      animalsBasics: "Animaux",
      birds: "Oiseaux",
      buildings: "Bâtiments",
      closeFamily: "Famille proche",
      clothesBasics: "Vêtements 1",
      constructionMaterials: "Matériaux",
      constructionTools: "Outils",
      days: "Jours",
      drinks: "Boissons",
      earth: "La Terre",
      farmAnimals: "Animaux de la ferme",
      firstNumbers: "Premiers nombres",
      foodBasics: "Nourriture 1",
      foods: "Aliments",
      fruits: "Fruits",
      furniture: "Meubles",
      head: "Tête",
      house: "Maison",
      housing: "Se loger",
      humanBodyBasics: "Corps humain",
      humanBeings: "Êtres humains",
      identity: "Identité",
      insects: "Insectes",
      introduction: "Rencontre",
      largeNumbers: "Grands nombres",
      limbs: "Membres",
      mainColors: "Couleurs 1",
      mammals1: "Mammifères",
      months: "Mois",
      moreClothes: "Vêtements 2",
      moreFruitsAndVegetables: "Fruits et légumes 2",
      moreNumbers: "Nombres suivants",
      natureBasics: "Nature",
      organs: "Organes",
      plants: "Plantes",
      rooms: "Pièces",
      sea: "Mer",
      seaAnimals: "Animaux marins",
      senses: "Sens",
      timeBasics: "Temps 1",
      timeDescription1: "Temps 2",
      timeDescription2: "Temps 3",
      timeDivisions: "Mesurer le temps",
      town: "Ville",
      transports: "Transports",
      trees: "Arbres",
      universe: "Univers",
      vegetables: "Légumes",
      vegetalBasics: "Végétaux",
      weather1: "Météo 1",
      weather2: "Météo 2",
    },
    translateIn: "Traduis en ",
    french: "français",
    english: "anglais",
    correct: [
      "Excellent",
      "C'est exact",
      "Parfait",
      "Rien à dire",
      "Impressionnant",
      "Dans la cible",
      "Bien",
      "Très bien",
      "Tout à fait",
      "Facile",
      "Bien joué",
      "Joli",
      "Exactement",
      "Merveilleux",
      "Formidable",
      "Bravo",
      "Et voilà",
    ],
    correctAnswer: "Bonne réponse",
    noMistake: "Félicitations, tu n'as fait aucune erreur !",
    oneMistake: "Bravo, c'est presque parfait !",
    oneMistakeInstruction: "Fais attention à ce mot :",
    moreMistakes: "Prends un moment pour apprendre ces mots :",
    masculine: "masculin",
    feminine: "féminin",
    singular: "singulier",
    plural: "pluriel",
    definite: "défini",
    indefinite: "indéfini",
    revision: "Révisions",
  },
};

export const LanguageContext = React.createContext(
  languages.english // default value
);
